title: HackLab
baseurl: ""
# theme: just-the-docs
permalink: '/:title'
color_scheme: dark

url: https://just-the-docs.github.io

aux_links:
  HackLab on Github: https://github.com/AlienWolfX/HackLab

aux_links_new_tab: true

# aux_buttons:
#   - title: "GitHub"
#     color: 'purple'
#     icon: 'github'
#     link: '//github.com/AlienWolfX/HackLab'

enable_copy_code_button: true

plugins:
  - jekyll-seo-tag
  # - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-default-layout
  
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

collections:
  usb_boards:
    permalink: "/:path/"
    output: true

just_the_docs:
  collections:
    usb_boards:
      name: USB Boards
      nav_fold: true
    # routers:
    #   name: Routers
    #   nav_fold: true

last_edit_timestamp_script: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright Allen Cruiz &copy; 2023-2024. The documentation hereby found is distributed under the terms of the <a href=\"https://github.com/AlienWolfX/HackLab/blob/main/LICENSE\">MIT License</a>"